### PR TITLE
Correct output of multidimensional datasets when using parallel HDF5

### PR DESCRIPTION
**Pull request by jchelly**
This addresses #24. When writing multidimensional output datasets in parallel mode the offsets into the dataset were calculated incorrectly.

There were multiple copies of the write_dataset_nd method in hdfitems.h, one templated and one taking a void * pointer for the input data. Rather than fix them both I've made the templated version just call the void * version with the data type parameter set. This is how it already works for 1D datasets.

Still needs testing.

### CODE REVIEW

**Comment by rtobar** [comment]
@jchelly am I correct to assume that when you say "still needs testing" you are performing such tests? I don't want to duplicate efforts, so if you are already on top of this we'll wait until your assessment comes back.

**Comment by jchelly** [comment]
Yes, sorry, I'm testing it. So far I've picked a few halos and checked that I can reproduce the density profiles in the velociraptor output by reading the snapshot file in python and counting particles in spherical shells. My calculation agrees with velociraptor exactly in the few cases I've looked. I'll try to repeat that for all the halos in the snapshot.

**Comment by rtobar** [comment]
> Yes, sorry, I'm testing it

Awesome, I just wanted to confirm if I had understood correctly, that's all :). Good luck with the tests!

**Comment by jchelly** [comment]
I believe this is working correctly. The density profiles of all halos in the run I'm using for testing agree exactly with my python code (they didn't before) and the other halo properties are not affected by these changes.

**Comment by rtobar** [comment]
Great, thanks for fixing this! I was looking at the changes, at it took me a while to figure out that the `rank` parameter of `write_dataset_nd` is actually the number of dimensions and not the rank of the application in a different communicator.

After making sense of that, I agree the changes look correct, which is also backed up by your tests and observations.

**Pull request merged**
