### PR TITLE
Hot gas properties

### PR DESCRIPTION
**Pull request by rtobar**
This is the set of changes implemented by @cdplagos to add hot gas properties to the VR outputs.

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
Is it at a point where you would want another round of testing?

**Comment by rtobar** [comment]
@cdplagos mentioned that @edoaltamura's tests showed this feature was working as expected. However, the Travis CI tests triggered by this PR highlighted a small problem that needs to be fixed prior to merging back to the `master`. While this is fixed you are most welcome to test this again if required though, and confirm that this is good to go.

**Comment by rtobar** [comment]
@MatthieuSchaller the problem has been fixed. Please feel free to perform further tests, and please let us know if on your side you are happy to have this merged to the `master` branch.

**Comment by rtobar** [comment]
@MatthieuSchaller @edoaltamura I'm coming back to this to ask for confirmation on whether you are happy with these changes or not, otherwise this PR will continue dangling. If you are fine with how things look I will merge the `hot_gas_properties` branch back to `master`; if you think there are still issues or missing bits please let us know.

**Comment by MatthieuSchaller** [comment]
Thanks for reminding me. 

I will confirm at the weekend whether the OpenMP and non-OpenMP versions match in their results. This was the last thing I wanted to test here. Just waiting for the cosma system to finish going through maintenance.

@edoaltamura, could you confirm whether the numbers you get out of this branch match what you get from your scripts?

**Comment by MatthieuSchaller** [comment]
Sorry for the time this has taken. I have now run this on the same snapshot once compiled with OpenMP and once without (no MPI) and found differences in the new fields.

version: 9f1e28c7e37d4a23e06b87acda8b6bf9338b56ff

command line: `stf -C vrconfig_3dfof_subhalos_SO_hydro.cfg -i baham_0036 -o halos_0036 -I 2`

Config: /cosma7/data/dp004/jlvc76/BAHAMAS/Roi_run/vrconfig_3dfof_subhalos_SO_hydro.cfg
Input: /cosma7/data/dp004/jlvc76/BAHAMAS/Roi_run/baham_0036.hdf5

output with OpenMP: /cosma7/data/dp004/jlvc76/BAHAMAS/Roi_run/halos_omp_0036.properties.0
output without OpenMP: /cosma7/data/dp004/jlvc76/BAHAMAS/Roi_run/halos_0036.properties.0

(I have not checked which one is correct, if any)

I can copy these elsewhere if that's helpful. Or run different things. Just let me know.

One additional question: Should I worry that the new parameters can be left out of the parameter file and the code won't complain?

**Comment by MatthieuSchaller** [comment]
It looks like the fixes made to the SO_xxxx quantities have not been applied in this branch. Might be fixed after a merge but maybe we should test this first.

**Comment by rtobar** [comment]
@MatthieuSchaller that's right, we haven't merged those fixes yet; the merge conflict is non-trivial though so it will take some close looking to make sure things are correctly put together. I'll update you when I have something.

**Comment by MatthieuSchaller** [comment]
@edoaltamura, do you have a script that computes the hot gas properties from the snapshots directly? I could use it to check the catalogs.

**Comment by edoaltamura** [comment]
Sure @MatthieuSchaller, you can use this to check the hot gas mass inside `R500crit`. The `if Mhot500c_key in h5file.keys()` statement switches between manual calculation and VR import.
```python
import sys
import os
import unyt
import numpy as np
from typing import Tuple
import h5py as h5

def process_single_halo(
        path_to_snap: str,
        path_to_catalogue: str
) -> Tuple[unyt.unyt_quantity]:
    # Read in halo properties
    with h5.File(f'{path_to_catalogue}', 'r') as h5file:
        M500c = unyt.unyt_quantity(h5file['/SO_Mass_500_rhocrit'][0] * 1.e10, unyt.Solar_Mass)
        R500c = unyt.unyt_quantity(h5file['/SO_R_500_rhocrit'][0], unyt.Mpc)

        # If the hot gas mass already computed by VR, use that instead of calculating it
        Mhot500c_key = "SO_Mass_gas_highT_1.000000_times_500.000000_rhocrit"

        if Mhot500c_key in h5file.keys():
            Mhot500c = unyt.unyt_quantity(h5file[f'/{Mhot500c_key}'][0] * 1.e10, unyt.Solar_Mass)

        else:
            XPotMin = unyt.unyt_quantity(h5file['/Xcminpot'][0], unyt.Mpc)
            YPotMin = unyt.unyt_quantity(h5file['/Ycminpot'][0], unyt.Mpc)
            ZPotMin = unyt.unyt_quantity(h5file['/Zcminpot'][0], unyt.Mpc)

            import swiftsimio as sw

            # Read in gas particles
            mask = sw.mask(f'{path_to_snap}', spatial_only=False)
            region = [[XPotMin - R500c, XPotMin + R500c],
                      [YPotMin - R500c, YPotMin + R500c],
                      [ZPotMin - R500c, ZPotMin + R500c]]
            mask.constrain_spatial(region)
            mask.constrain_mask(
                "gas", "temperatures",
                1.e5* mask.units.temperature,
                1.e12 * mask.units.temperature
            )
            data = sw.load(f'{path_to_snap}', mask=mask)
            posGas = data.gas.coordinates
            massGas = data.gas.masses

            # Select hot gas within sphere
            deltaX = posGas[:, 0] - XPotMin
            deltaY = posGas[:, 1] - YPotMin
            deltaZ = posGas[:, 2] - ZPotMin
            deltaR = np.sqrt(deltaX ** 2 + deltaY ** 2 + deltaZ ** 2)
            index = np.where(deltaR < R500c)[0]
            Mhot500c = np.sum(massGas[index])
            Mhot500c = Mhot500c.to(unyt.Solar_Mass)

    return M500c, Mhot500c
```

**Comment by rtobar** [comment]
@MatthieuSchaller I was wrong: I had forgotten, and after closer examination we *had* merged Pascal's fixes for the SO quantities. His original commit (bf9d9a1) contained two main changes (apart from some code refactoring, which made the merge more tricky) in the main evaluation routine: firstly, the value for `rc` changed from `posparts[indices[j]].Length()` to `radii[indices[j]]`, and secondly a number of values in the `PartData` objects are now initialised to 0. These two changes *were* merged into `hot_gas_properties` first in 9af51df and then in 862bcac, so the version you tested should have those.

About the differences between OpenMP/non-OpenMP runs: I had a quick look at the output files you pointed at and inspected some of the values. `SO_Mass_star_500_rhocrit` indeed looks different, so I'll try to investigate a bit more what could be going on. I'd tend to assume the OpenMP version is at fault, but I also don't have a clear idea on how to decide which values are correct and which aren't.

**Comment by rtobar** [comment]
@MatthieuSchaller you also asked about the new parameters and if those can be left out of the parameter file. I **think** that's the case; if the parameters are not present then by default the additional properties are not calculated.

**Comment by MatthieuSchaller** [comment]
@rtobar I can confirm that the non-OpenMP catalog is correct. If I compare the values of `SO_Mass_gas_highT_1.000000_times_500.00000_rhocrit` to the values computed "by hand" from Edo's script above then they are all correct. 
The OpenMP version fails the test. 

Could it be that the OpenMP fix in Pascal's branch was applied to the "normal" quantities but not to the SO_xxx ones? I think they use a different mechanism since the user can specify a bunch of so-called over-densities (e.g. 500 x rho_crit) that they want things computed for?
This would explain why `SO_Mass_star_500_rhocrit` is also wrong in this branch, despite it having nothing to do with the changes introduced here. 

If we think this is the case, then I guess this can be merged and the more general investigation of the SO_ properties with OpenMP switched on can start/resume.

**Comment by MatthieuSchaller** [comment]
Also, thanks @edoaltamura for the script!

**Comment by rtobar** [comment]
Thanks @MatthieuSchaller for the extra information. I agree that the OpenMP issue is more widespread than just to the addition of these new properties; as you mention it affects a number of pre-existing properties also on the `master` branch. I'll open a new ticket to keep track of this issue.

Since we are happy with how things loop in the serial case I'll then merge this branch back to the `master.

**Pull request merged**
